version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
